In [4]:
import numpy as np

In [5]:
def isPrime(n:int)->bool:
    """This function is to determine whether or not the given number is a prime number"""

    if n <= 1:
        return False
    
    for i in range(2,(n//2)+1):
        if n % i == 0:
            return False
    
    return True

In [6]:
def pi_list(n:int)->list:
    """This function is to generate a list of prime numbers starting from 2 to a given value n"""

    list_primes = []
    for i in range(0,n+1):
        if isPrime(i):
            list_primes.append(i)

    return list_primes

In [7]:
def knodel_adjacency(n:int)->list:
    """This function defines the adjacency matrix for a given n-vertex knodel graph"""

    list_primes = pi_list(n)
    adjacency_matrix = np.zeros((2*n,2*n),dtype=int)

    for i in range(1,2*n+1):
        for j in range(1,2*n+1):

            if i <= n:
                if j> n:
                    if j-i+1 in list_primes or j-i+1-n in list_primes:
                        adjacency_matrix[i-1][j-1] = 1
            
            if i > n:
                if j <= n:
                    if i-j+1 in list_primes or i-j+1-n in list_primes:
                        adjacency_matrix[i-1][j-1] = 1

    return adjacency_matrix

In [8]:
adjacency_matrix = knodel_adjacency(7)
print(adjacency_matrix[0:7,7:])

[[0 1 1 0 1 0 1]
 [1 0 1 1 0 1 0]
 [0 1 0 1 1 0 1]
 [1 0 1 0 1 1 0]
 [0 1 0 1 0 1 1]
 [1 0 1 0 1 0 1]
 [1 1 0 1 0 1 0]]


In [9]:
print(adjacency_matrix[0:7,7:].transpose() == adjacency_matrix[7:,0:7])

[[ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]


In [10]:
n = int(input("Enter the number of vertices in the graph:"))
adj = knodel_adjacency(n)
adj[0:n,n:]


array([[0, 1, 1, 0, 1, 0, 1],
       [1, 0, 1, 1, 0, 1, 0],
       [0, 1, 0, 1, 1, 0, 1],
       [1, 0, 1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0, 1, 1],
       [1, 0, 1, 0, 1, 0, 1],
       [1, 1, 0, 1, 0, 1, 0]])

In [32]:
def isSafe(graph,v,pos,path):
    """This function is to check whether or not the next vertex can be accessed"""

    if graph[path[pos-1]][v] == 0:
        return False
    
    for vertex in path:
        if vertex == v:
            return False
        
    return True

In [33]:
def hamCycleUtil(graph,path,pos):

    if pos == len(graph):
        if graph[path[pos-1]][path[0]] == 1:
            return True
        else:
            return False
        
    for v in range(1,len(graph)):
 
        if isSafe(graph,v,pos,path) == True:

            path[pos] = v
            #graph[path[pos-1]][v] = 0
 
            if hamCycleUtil(graph,path, pos+1) == True:
                    return True
 
            path[pos] = -1
            #graph[path[pos-1]][v] = 1
 
        return False

In [34]:
def HamCycle(graph):
    path = [-1]*len(graph)

    path[0] = 0

    if hamCycleUtil(graph,path,1) == False:
        return False
    return True

In [35]:
def numHamCycles(graph):

    while 1 in graph[0]:
        count = 0

        if HamCycle(graph) == False:
            return count
        else:
            count += 1

In [36]:
graph = knodel_adjacency(7)
#print(graph)
HamCycle(graph)

[[0 0 0 0 0 0 0 0 1 1 0 1 0 1]
 [0 0 0 0 0 0 0 1 0 1 1 0 1 0]
 [0 0 0 0 0 0 0 0 1 0 1 1 0 1]
 [0 0 0 0 0 0 0 1 0 1 0 1 1 0]
 [0 0 0 0 0 0 0 0 1 0 1 0 1 1]
 [0 0 0 0 0 0 0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 1 1 0 1 0 1 0]
 [0 1 0 1 0 1 1 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0 0 0 0 0 0 0]
 [1 1 0 1 0 1 0 0 0 0 0 0 0 0]
 [0 1 1 0 1 0 1 0 0 0 0 0 0 0]
 [1 0 1 1 0 1 0 0 0 0 0 0 0 0]
 [0 1 0 1 1 0 1 0 0 0 0 0 0 0]
 [1 0 1 0 1 1 0 0 0 0 0 0 0 0]]


False