In [45]:
import numpy as np

In [46]:
def isPrime(n:int)->bool:
    """This function is to determine whether or not the given number is a prime number"""

    if n <= 1:
        return False
    
    for i in range(2,(n//2)+1):
        if n % i == 0:
            return False
    
    return True

In [47]:
def pi_list(n:int)->list:
    """This function is to generate a list of prime numbers starting from 2 to a given value n"""

    list_primes = []
    for i in range(0,n+1):
        if isPrime(i):
            list_primes.append(i)

    return list_primes

In [48]:
def knodel_adjacency(n:int)->list:
    """This function defines the adjacency matrix for a given n-vertex knodel graph"""

    list_primes = pi_list(n)
    adjacency_matrix = np.zeros((2*n,2*n),dtype=int)

    for i in range(1,2*n+1):
        for j in range(1,2*n+1):

            if i <= n:
                if j> n:
                    if j-i+1 in list_primes or j-i+1-n in list_primes:
                        adjacency_matrix[i-1][j-1] = 1
            
            if i > n:
                if j <= n:
                    if i-j+1 in list_primes or i-j+1-n in list_primes:
                        adjacency_matrix[i-1][j-1] = 1

    return adjacency_matrix

In [49]:
adjacency_matrix = knodel_adjacency(7)
print(adjacency_matrix[0:7,7:])

[[0 1 1 0 1 0 1]
 [1 0 1 1 0 1 0]
 [0 1 0 1 1 0 1]
 [1 0 1 0 1 1 0]
 [0 1 0 1 0 1 1]
 [1 0 1 0 1 0 1]
 [1 1 0 1 0 1 0]]


In [50]:
print(adjacency_matrix[0:7,7:].transpose() == adjacency_matrix[7:,0:7])

[[ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]


In [51]:
n = int(input("Enter the number of vertices in the graph:"))
print(knodel_adjacency(n))


[[0 0 0 0 0 0 1 1 0 1]
 [0 0 0 0 0 1 0 1 1 0]
 [0 0 0 0 0 0 1 0 1 1]
 [0 0 0 0 0 1 0 1 0 1]
 [0 0 0 0 0 1 1 0 1 0]
 [0 1 0 1 1 0 0 0 0 0]
 [1 0 1 0 1 0 0 0 0 0]
 [1 1 0 1 0 0 0 0 0 0]
 [0 1 1 0 1 0 0 0 0 0]
 [1 0 1 1 0 0 0 0 0 0]]
