In [7]:
import numpy as np

In [8]:
def isPrime(n:int)->bool:
    """This function is to determine whether or not the given number is a prime number"""

    if n <= 1:
        return False
    
    for i in range(2,(n//2)+1):
        if n % i == 0:
            return False
    
    return True

In [9]:
def pi_list(n:int)->list:
    """This function is to generate a list of prime numbers starting from 2 to a given value n"""

    list_primes = []
    for i in range(0,n+1):
        if isPrime(i):
            list_primes.append(i)

    return list_primes

In [10]:
def knodel_adjacency(n:int)->list:
    """This function defines the adjacency matrix for a given n-vertex knodel graph"""

    list_primes = pi_list(n)
    adjacency_matrix = np.zeros((2*n,2*n),dtype=int)

    for i in range(1,2*n+1):
        for j in range(1,2*n+1):

            if i <= n:
                if j> n:
                    if j-i+1 in list_primes or j-i+1-n in list_primes:
                        adjacency_matrix[i-1][j-1] = 1
            
            if i > n:
                if j <= n:
                    if i-j+1 in list_primes or i-j+1-n in list_primes:
                        adjacency_matrix[i-1][j-1] = 1

    return adjacency_matrix

In [11]:
adjacency_matrix = knodel_adjacency(7)
print(adjacency_matrix[0:7,7:])

[[0 1 1 0 1 0 1]
 [1 0 1 1 0 1 0]
 [0 1 0 1 1 0 1]
 [1 0 1 0 1 1 0]
 [0 1 0 1 0 1 1]
 [1 0 1 0 1 0 1]
 [1 1 0 1 0 1 0]]


In [12]:
print(adjacency_matrix[0:7,7:].transpose() == adjacency_matrix[7:,0:7])

[[ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]


In [13]:
n = int(input("Enter the number of vertices in the graph:"))
print(knodel_adjacency(n))


[[0 0 0 0 0 0 0 0 1 1 0 1 0 1]
 [0 0 0 0 0 0 0 1 0 1 1 0 1 0]
 [0 0 0 0 0 0 0 0 1 0 1 1 0 1]
 [0 0 0 0 0 0 0 1 0 1 0 1 1 0]
 [0 0 0 0 0 0 0 0 1 0 1 0 1 1]
 [0 0 0 0 0 0 0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 1 1 0 1 0 1 0]
 [0 1 0 1 0 1 1 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0 0 0 0 0 0 0]
 [1 1 0 1 0 1 0 0 0 0 0 0 0 0]
 [0 1 1 0 1 0 1 0 0 0 0 0 0 0]
 [1 0 1 1 0 1 0 0 0 0 0 0 0 0]
 [0 1 0 1 1 0 1 0 0 0 0 0 0 0]
 [1 0 1 0 1 1 0 0 0 0 0 0 0 0]]


In [14]:
def isSafe(v,graph,path,pos):
    """This function is to check whether or not the next vertex can be accessed"""

    if graph[path[pos-1]][v] == 0:
        return False
    
    for i in range(pos):
        if path[i] == v:
            return False
        
    return True

In [15]:
def FindHamCycle(graph,pos,path,visited,hasCycle):

    if pos == len(graph):

        if graph[path[-1]][path[0]] != 0:
            path.append(0)
            for i in range(len(path)):
                print(path[i],end=" ")
            print()

            path.pop()

            hasCycle = True
            return
    
    for v in range(len(graph)):

        if isSafe(v,graph,path,pos) and not visited[v]:

            path.append(v)
            visited[v] = True

            FindHamCycle(graph,pos + 1,path,visited,hasCycle)

            visited[v] = False
            path.pop()


In [16]:
def hamCycle(graph,hasCycle):

    hasCycle = False

    path = []
    path.append(0)

    visited = [False]*len(graph)

    for i in range(len(visited)):
        visited[i] = False

    visited[0] = True

    FindHamCycle(graph,1,path,visited,hasCycle)

    if hasCycle:
        print("No  Hamiltonian Cycle possible")
        return
    

In [17]:
hasCycle = False
graph = knodel_adjacency(7)
hamCycle(graph,hasCycle)

0 8 2 10 1 7 6 12 4 13 5 9 3 11 0 
0 8 2 10 1 7 6 12 4 13 5 11 3 9 0 
0 8 2 10 1 9 3 7 6 12 4 13 5 11 0 
0 8 2 10 1 9 3 11 5 7 6 12 4 13 0 
0 8 2 10 1 9 5 11 3 7 6 12 4 13 0 
0 8 2 10 1 9 5 13 4 12 6 7 3 11 0 
0 8 2 10 4 12 6 7 1 9 3 11 5 13 0 
0 8 2 10 4 13 5 7 6 12 1 9 3 11 0 
0 8 2 10 4 13 5 9 1 7 6 12 3 11 0 
0 8 2 10 4 13 5 9 1 12 6 7 3 11 0 
0 8 2 10 4 13 5 11 3 7 6 12 1 9 0 
0 8 2 10 4 13 5 11 3 12 6 7 1 9 0 
0 8 2 10 6 7 1 9 3 12 4 13 5 11 0 
0 8 2 10 6 7 1 9 5 11 3 12 4 13 0 
0 8 2 10 6 7 1 9 5 13 4 12 3 11 0 
0 8 2 10 6 7 1 12 4 13 5 9 3 11 0 
0 8 2 10 6 7 1 12 4 13 5 11 3 9 0 
0 8 2 10 6 7 3 9 1 12 4 13 5 11 0 
0 8 2 10 6 7 3 11 5 9 1 12 4 13 0 
0 8 2 10 6 7 3 11 5 13 4 12 1 9 0 
0 8 2 10 6 7 5 11 3 9 1 12 4 13 0 
0 8 2 10 6 7 5 13 4 12 1 9 3 11 0 
0 8 2 10 6 12 4 13 5 7 1 9 3 11 0 
0 8 2 10 6 12 4 13 5 9 1 7 3 11 0 
0 8 2 10 6 12 4 13 5 11 3 7 1 9 0 
0 8 2 11 3 7 1 10 6 12 4 13 5 9 0 
0 8 2 11 3 7 1 12 6 10 4 13 5 9 0 
0 8 2 11 3 7 5 9 1 10 6 12 4 13 0 
0 8 2 11 3 7 5 9 1 1